FROM openjdk:11

RUN mkdir -p /home/app/covidradar-madrid

COPY ./covidradar-madrid-0.0.1-SNAPSHOT.jar /home/app/covidradar-madrid

CMD ["java", "-jar", "/home/app/covidradar-madrid/covidradar-madrid-0.0.1-SNAPSHOT.jar"]