version: '3'
networks:
  default:
    external:
      name: coivd-radar-madrid
services:
  mongodb: 
    image: mongo
    ports:
      - 27017:27017
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=HJ/W9K}2XamRVvPj
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=7[w4]v7F\tb#Xs2_
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=HJ/W9K}2XamRVvPj
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
  backend:
    image: covid-radar:0.1
    ports: 
      - 8080:8080
    depends_on:
      - mongo-express
    links:
      - mongodb 