version: 2.0

jobs:

  build:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: ./mvnw -Dmaven.test.skip=true package -P release
      - persist_to_workspace:
         root: .
         paths:
           - .

  test:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: ./mvnw verify
      - run:
          name: upload test coverage report
          command: |
            export CODECOV_TOKEN='80264ac9-4da7-4af5-b555-1c9e3c53de8f'
            bash <(curl -s https://codecov.io/bash) 

  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: target contents
          command: ls ./target      
      - run:
          name: Install awscli
          command: |
            sudo pip install awsebcli --upgrade
      - run:
          name: Create AWS credentials manually
          command: |
            mkdir ~/.aws
            touch ~/.aws/config
            chmod 600 ~/.aws/config
            echo "[profile eb-cli]" > ~/.aws/config
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
      - run:
          name: Deploy to EB if branch is Production
          command: |
            eb deploy Covidradarmadrid-env  --debug -l $CIRCLE_BUILD_NUM-deploy 

         
 
workflows:
  version: 2
  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: production

