version: '2.1'
orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0
  maven: circleci/maven@1.1.0
workflows:
  elastic-beanstalk-workflow:
    jobs:
      - maven/test # checks that the program will build and tests it
      - install:  # packages program into .jar for deployment to eb
          steps:
            - run:
              name: install
              command: mvn clean install -P prod
          filters:
            branches:
              only:
                - production
          requires: maven/test
      - eb/deploy: #deploys to ews/elastic beanstalk environment
          context: aws-eb
          environment-name: Covidradarmadrid-env
          filters:
            branches:
              only:
                - production
          label: version-<<pipeline.number>>
          requires:
            - install

