version: 2.0

jobs:
  test:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  
    steps:
      - checkout
      - attach_workspace:
          at: ./target
      - run: ./mvnw test

  build:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_KEY 
    steps:
      - checkout
      - run: ./mvnw -Dmaven.test.skip=true package -P prod
      - persist_to_workspace:
         root: ./
         paths:
           - target/

  deploy:
    docker:
      - image: mini/eb-cli
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_KEY
    steps:
      - attach_workspace:
            at: ./target
      - run: |
          eb init
          eb deploy Covidradarmadrid-env
           
         
 
workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: production


