version: 2.0

jobs:
  test:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - attach_workspace:
          at: ./target
      - run: ./mvnw test

  build:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: ./mvnw -Dmaven.test.skip=true package -P prod
      - persist_to_workspace:
         root: ./
         paths:
           - target/

  deploy:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: Deploy to EB if branch is Production
          command: |
            eb deploy -l $CIRCLE_BUILD_NUM-deploy 

         
 
workflows:
  version: 2
  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: production


