version: '2.1'
orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0
  maven: circleci/maven@1.1.0
workflows:
  elastic-beanstalk-workflow:
    jobs:
      - maven/test: # checks that the program will build, tests it, and packages it as a .jar
        command: clean install -P prod
          requires: maven/test
      - eb/deploy: #deploys to ews/elastic beanstalk environment
        context: aws-eb
        environment-name: Covidradarmadrid-env
        filters:
          branches:
            only:
              - production
        label: version-<<pipeline.number>>
        requires:
          - maven/test

